apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - path: argocd/applications
      repoURL: https://github.com/lets-store-it/infrastructure.git
