authentik:
  secret_key: "PleaseGenerateA50CharKey"
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.store-it.ru

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"
  primary:
    extendedConfiguration: |
      max_connections = 500
    resourcesPreset: "none"
    persistence:
      enabled: true
      storageClass: csi-ceph-ssd-me1

redis:
  enabled: true
  master:
    persistence:
      storageClass: csi-ceph-ssd-me1
