authentik:
  secret_key: "PleaseGenerateA50CharKey"
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.store-it.ru

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"

redis:
  enabled: true
