apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storeit
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storeit
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/lets-store-it/backend:50ebe9f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
          envFrom:
            - secretRef:
                name: backend-config
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/json
