apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: storeit-pg
spec:
  instances: 1
  storage:
    size: 2Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: csi-ceph-ssd-me1
