apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: storeit-pg
spec:
  instances: 3
  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-ceph-ssd-me1
