---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: backend
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: storeit
      app.kubernetes.io/component: backend
