---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: authentik
  project: default
  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io
      targetRevision: 2024.12.1
      helm:
        valueFiles:
          - $values/argocd/authentik/values.yaml
    - repoURL: https://github.com/lets-store-it/infrastructure.git
      ref: values
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
