---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  sources:
    - chart: ingress-nginx
      helm:
        valueFiles:
          - $values/argocd/ingress-nginx/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.0
    - repoURL: https://github.com/lets-store-it/infrastructure.git
      ref: values
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    automated: {}
