---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: operators
  project: default
  sources:
    - repoURL: https://github.com/lets-store-it/infrastructure.git
      ref: values
    - chart: strimzi-kafka-operator
      targetRevision: 0.46.0
      repoURL: https://strimzi.io/charts
      # helm:
      #   valueFiles:
      #     - $values/argocd/strimzi-operator/values.yaml
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated: {}
